___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [ ]:
import numpy as np 

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list=[5,10,15,20,25]
arr = np.array(my_list)
arr

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

In [ ]:
np.ones((4,4),dtype='int')*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [ ]:
np.full([4,4],7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [38]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,24,25, dtype="int").reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.rand(5)

array([0.71507799, 0.12817946, 0.82526995, 0.56512908, 0.50357352])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.randn(25).reshape(5,5)

array([[-0.96182544, -0.7595247 , -1.33907709,  0.13527703,  1.61520547],
       [ 0.70526738, -0.21378499,  0.0867292 ,  3.30708026, -0.53325049],
       [ 2.10301809, -0.22238038, -0.98697518, -0.08754663, -1.1151851 ],
       [ 2.01967663, -1.57859811,  0.02508712, -1.2620871 , -0.685515  ],
       [ 0.49953879,  0.3730371 , -0.20302535, -0.26467419, -0.95240745]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50,12).reshape(3,4)

array([[43, 24, 28, 35],
       [41, 49, 27, 35],
       [47, 22, 23, 21]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr = np.array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [ ]:
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [ ]:
ranarr.reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [ ]:
#reshape with -1
ranarr.reshape(-1,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [40]:
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Create array below
mat= np.arange(1,17).reshape(4,4)
mat

#### 14. Write code that reproduces the output shown below.<br>

In [41]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [43]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [44]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [45]:
mat[:,2] = 77

In [46]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [47]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [48]:
mat[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [49]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [50]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [51]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [52]:
mat[mat<10]+mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [53]:
(mat[mat<10]+mat[mat>12]).std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [54]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [55]:
mat[:,2]=[3,7,11,15]

In [56]:
#print array here
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
mat[:,1].sum(axis=0)

32

#### 23. Get the median,mean and std of 3rd row from array above

In [58]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
mat[2]

array([ 9, 10, 11, 12])

In [60]:
#median
np.median(mat[2])

10.5

In [61]:
#mean
np.mean(mat[2])

10.5

In [62]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [63]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [66]:
salary=pd.read_csv('Salaries.csv')

In [67]:
salary.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [68]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78778 entries, 0 to 78777
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Id                78778 non-null  int64  
 1   EmployeeName      78778 non-null  object 
 2   JobTitle          78778 non-null  object 
 3   BasePay           78777 non-null  float64
 4   OvertimePay       78777 non-null  float64
 5   OtherPay          78777 non-null  float64
 6   Benefits          42618 non-null  float64
 7   TotalPay          78777 non-null  float64
 8   TotalPayBenefits  78777 non-null  float64
 9   Year              78777 non-null  float64
 10  Notes             0 non-null      float64
 11  Agency            78777 non-null  object 
 12  Status            0 non-null      float64
dtypes: float64(9), int64(1), object(3)
memory usage: 7.8+ MB


In [69]:
salary.describe()

Id        BasePay    OvertimePay  ...          Year  Notes  Status
count  78778.00000   78777.000000   78777.000000  ...  78777.000000    0.0     0.0
mean   39389.50000   69878.083936    5701.249934  ...   2011.615281    NaN     NaN
std    22741.39409   44607.098174   12654.006941  ...      0.620714    NaN     NaN
min        1.00000    -166.010000       0.000000  ...   2011.000000    NaN     NaN
25%    19695.25000   38631.030000       0.000000  ...   2011.000000    NaN     NaN
50%    39389.50000   66066.400000       0.000000  ...   2012.000000    NaN     NaN
75%    59083.75000  102242.980000    5393.520000  ...   2012.000000    NaN     NaN
max    78778.00000  319275.010000  245131.880000  ...   2013.000000    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [70]:
salary.Year.value_counts()

2012.0    36766
2011.0    36159
2013.0     5852
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [71]:
#max
salary.TotalPay.max()

567595.43

In [72]:
#avg
salary.TotalPay.mean()

79826.2837467841

**How many records are there which have TotalPay bigger than avg TotalPay**

In [73]:
salary["TotalPay"][salary.TotalPay > salary.TotalPay.mean()].value_counts()

123290.70    56
132242.50    49
105489.00    42
168419.82    27
97461.00     23
             ..
163404.38     1
201641.91     1
158310.00     1
132293.02     1
148859.07     1
Name: TotalPay, Length: 33174, dtype: int64

In [74]:
len(salary["TotalPay"][salary.TotalPay > salary.TotalPay.mean()].value_counts())

33174

**How much does ALBERT PARDINI make (including benefits)?**

In [75]:
salary["TotalPay"][salary["EmployeeName"]=="ALBERT PARDINI"]

2    335279.91
Name: TotalPay, dtype: float64

**Who is lowest paid person**

In [76]:
salary[salary.TotalPayBenefits==salary.TotalPayBenefits.min()]['EmployeeName']

36156        PAULETTE ADAMS
36157         KAUKAB MOHSIN
36158    JOSEPHINE MCCREARY
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [77]:
salary.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ...,
       'Civil Case Settlmnt Specialist', 'IT Operations Support Admin II',
       'Police Officer '], dtype=object)

**List 3 least common Jobs**

In [78]:
salary["JobTitle"].value_counts().tail(3)

ASSESSOR                           1
PRINCIPAL RECREATION SUPERVISOR    1
SPECIAL ASSISTANT XV               1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [81]:
salary[(salary.TotalPayBenefits>salary.TotalPayBenefits.mean()) & (salary.Year==2012)]['EmployeeName'].count()

19998

**How many people have the word Manager in their job title?**

In [82]:
def manager_func(x):
    if 'manager' in x.lower():
        return True
    else:
        return False

In [83]:
len(salary[salary.JobTitle.apply(lambda x:manager_func(x))])

2648

In [84]:
#use apply function here
len(salary[salary.JobTitle.apply(lambda x: True if 'manager' in x.lower() else False)])

2648

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [85]:
sal_new=salary.iloc[:,[0,1,2,7,8]]
sal_new.head()

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0   1     NATHANIEL FORD  ...  567595.43         567595.43
1   2       GARY JIMENEZ  ...  538909.28         538909.28
2   3     ALBERT PARDINI  ...  335279.91         335279.91
3   4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4   5    PATRICK GARDNER  ...  326373.19         326373.19

[5 rows x 5 columns]

In [86]:
sal_new

Id             EmployeeName  ...   TotalPay  TotalPayBenefits
0          1           NATHANIEL FORD  ...  567595.43         567595.43
1          2             GARY JIMENEZ  ...  538909.28         538909.28
2          3           ALBERT PARDINI  ...  335279.91         335279.91
3          4        CHRISTOPHER CHONG  ...  332343.61         332343.61
4          5          PATRICK GARDNER  ...  326373.19         326373.19
...      ...                      ...  ...        ...               ...
78773  78774       Catheryn  Williams  ...  130805.71         170030.16
78774  78775              Suan  Chang  ...  131363.11         170030.11
78775  78776             Eric  Chiang  ...  132951.32         170022.83
78776  78777               Alan  Lamb  ...  133439.08         170010.19
78777  78778  Amalia  Barcena-Bosnich  ...        NaN               NaN

[78778 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [87]:
sal_new=sal_new.loc[:,'EmployeeName':'TotalPayBenefits']
sal_new

EmployeeName  ... TotalPayBenefits
0               NATHANIEL FORD  ...        567595.43
1                 GARY JIMENEZ  ...        538909.28
2               ALBERT PARDINI  ...        335279.91
3            CHRISTOPHER CHONG  ...        332343.61
4              PATRICK GARDNER  ...        326373.19
...                        ...  ...              ...
78773       Catheryn  Williams  ...        170030.16
78774              Suan  Chang  ...        170030.11
78775             Eric  Chiang  ...        170022.83
78776               Alan  Lamb  ...        170010.19
78777  Amalia  Barcena-Bosnich  ...              NaN

[78778 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [88]:
salary[(salary.TotalPayBenefits>salary.TotalPayBenefits.min()) & 
       (salary.TotalPayBenefits<salary.TotalPayBenefits.mean())]['EmployeeName']

10324    CHRISTOPHER KERN
10325         DENNIS KWAN
10326     JOSEFINA TOLOSA
10327    JONATHAN STAPLES
10328     ANDREW PHILLIPS
               ...       
72920    Charles Williams
72921        John Carajan
72922         John Draper
72923        Cherise Wong
72924        Donald Clark
Name: EmployeeName, Length: 42600, dtype: object